require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IncidentTypesController do

  # This should return the minimal set of attributes required to create a valid
  # IncidentType. As you add validations to IncidentType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IncidentTypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all incident_types as @incident_types" do
      incident_type = IncidentType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:incident_types).should eq([incident_type])
    end
  end

  describe "GET show" do
    it "assigns the requested incident_type as @incident_type" do
      incident_type = IncidentType.create! valid_attributes
      get :show, {:id => incident_type.to_param}, valid_session
      assigns(:incident_type).should eq(incident_type)
    end
  end

  describe "GET new" do
    it "assigns a new incident_type as @incident_type" do
      get :new, {}, valid_session
      assigns(:incident_type).should be_a_new(IncidentType)
    end
  end

  describe "GET edit" do
    it "assigns the requested incident_type as @incident_type" do
      incident_type = IncidentType.create! valid_attributes
      get :edit, {:id => incident_type.to_param}, valid_session
      assigns(:incident_type).should eq(incident_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IncidentType" do
        expect {
          post :create, {:incident_type => valid_attributes}, valid_session
        }.to change(IncidentType, :count).by(1)
      end

      it "assigns a newly created incident_type as @incident_type" do
        post :create, {:incident_type => valid_attributes}, valid_session
        assigns(:incident_type).should be_a(IncidentType)
        assigns(:incident_type).should be_persisted
      end

      it "redirects to the created incident_type" do
        post :create, {:incident_type => valid_attributes}, valid_session
        response.should redirect_to(IncidentType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved incident_type as @incident_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        IncidentType.any_instance.stub(:save).and_return(false)
        post :create, {:incident_type => {}}, valid_session
        assigns(:incident_type).should be_a_new(IncidentType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IncidentType.any_instance.stub(:save).and_return(false)
        post :create, {:incident_type => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested incident_type" do
        incident_type = IncidentType.create! valid_attributes
        # Assuming there are no other incident_types in the database, this
        # specifies that the IncidentType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IncidentType.any_instance.should_receive(:update).with({'these' => 'params'})
        put :update, {:id => incident_type.to_param, :incident_type => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested incident_type as @incident_type" do
        incident_type = IncidentType.create! valid_attributes
        put :update, {:id => incident_type.to_param, :incident_type => valid_attributes}, valid_session
        assigns(:incident_type).should eq(incident_type)
      end

      it "redirects to the incident_type" do
        incident_type = IncidentType.create! valid_attributes
        put :update, {:id => incident_type.to_param, :incident_type => valid_attributes}, valid_session
        response.should redirect_to(incident_type)
      end
    end

    describe "with invalid params" do
      it "assigns the incident_type as @incident_type" do
        incident_type = IncidentType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IncidentType.any_instance.stub(:save).and_return(false)
        put :update, {:id => incident_type.to_param, :incident_type => {}}, valid_session
        assigns(:incident_type).should eq(incident_type)
      end

      it "re-renders the 'edit' template" do
        incident_type = IncidentType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IncidentType.any_instance.stub(:save).and_return(false)
        put :update, {:id => incident_type.to_param, :incident_type => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested incident_type" do
      incident_type = IncidentType.create! valid_attributes
      expect {
        delete :destroy, {:id => incident_type.to_param}, valid_session
      }.to change(IncidentType, :count).by(-1)
    end

    it "redirects to the incident_types list" do
      incident_type = IncidentType.create! valid_attributes
      delete :destroy, {:id => incident_type.to_param}, valid_session
      response.should redirect_to(incident_types_url)
    end
  end

end
