require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MapLinksController do

  # This should return the minimal set of attributes required to create a valid
  # MapLink. As you add validations to MapLink, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MapLinksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all map_links as @map_links" do
      map_link = MapLink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:map_links).should eq([map_link])
    end
  end

  describe "GET show" do
    it "assigns the requested map_link as @map_link" do
      map_link = MapLink.create! valid_attributes
      get :show, {:id => map_link.to_param}, valid_session
      assigns(:map_link).should eq(map_link)
    end
  end

  describe "GET new" do
    it "assigns a new map_link as @map_link" do
      get :new, {}, valid_session
      assigns(:map_link).should be_a_new(MapLink)
    end
  end

  describe "GET edit" do
    it "assigns the requested map_link as @map_link" do
      map_link = MapLink.create! valid_attributes
      get :edit, {:id => map_link.to_param}, valid_session
      assigns(:map_link).should eq(map_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MapLink" do
        expect {
          post :create, {:map_link => valid_attributes}, valid_session
        }.to change(MapLink, :count).by(1)
      end

      it "assigns a newly created map_link as @map_link" do
        post :create, {:map_link => valid_attributes}, valid_session
        assigns(:map_link).should be_a(MapLink)
        assigns(:map_link).should be_persisted
      end

      it "redirects to the created map_link" do
        post :create, {:map_link => valid_attributes}, valid_session
        response.should redirect_to(MapLink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved map_link as @map_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        MapLink.any_instance.stub(:save).and_return(false)
        post :create, {:map_link => {}}, valid_session
        assigns(:map_link).should be_a_new(MapLink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MapLink.any_instance.stub(:save).and_return(false)
        post :create, {:map_link => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested map_link" do
        map_link = MapLink.create! valid_attributes
        # Assuming there are no other map_links in the database, this
        # specifies that the MapLink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MapLink.any_instance.should_receive(:update).with({'these' => 'params'})
        put :update, {:id => map_link.to_param, :map_link => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested map_link as @map_link" do
        map_link = MapLink.create! valid_attributes
        put :update, {:id => map_link.to_param, :map_link => valid_attributes}, valid_session
        assigns(:map_link).should eq(map_link)
      end

      it "redirects to the map_link" do
        map_link = MapLink.create! valid_attributes
        put :update, {:id => map_link.to_param, :map_link => valid_attributes}, valid_session
        response.should redirect_to(map_link)
      end
    end

    describe "with invalid params" do
      it "assigns the map_link as @map_link" do
        map_link = MapLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MapLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => map_link.to_param, :map_link => {}}, valid_session
        assigns(:map_link).should eq(map_link)
      end

      it "re-renders the 'edit' template" do
        map_link = MapLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MapLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => map_link.to_param, :map_link => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested map_link" do
      map_link = MapLink.create! valid_attributes
      expect {
        delete :destroy, {:id => map_link.to_param}, valid_session
      }.to change(MapLink, :count).by(-1)
    end

    it "redirects to the map_links list" do
      map_link = MapLink.create! valid_attributes
      delete :destroy, {:id => map_link.to_param}, valid_session
      response.should redirect_to(map_links_url)
    end
  end

end
