require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SignTypesController do

  # This should return the minimal set of attributes required to create a valid
  # SignType. As you add validations to SignType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SignTypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sign_types as @sign_types" do
      sign_type = SignType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sign_types).should eq([sign_type])
    end
  end

  describe "GET show" do
    it "assigns the requested sign_type as @sign_type" do
      sign_type = SignType.create! valid_attributes
      get :show, {:id => sign_type.to_param}, valid_session
      assigns(:sign_type).should eq(sign_type)
    end
  end

  describe "GET new" do
    it "assigns a new sign_type as @sign_type" do
      get :new, {}, valid_session
      assigns(:sign_type).should be_a_new(SignType)
    end
  end

  describe "GET edit" do
    it "assigns the requested sign_type as @sign_type" do
      sign_type = SignType.create! valid_attributes
      get :edit, {:id => sign_type.to_param}, valid_session
      assigns(:sign_type).should eq(sign_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SignType" do
        expect {
          post :create, {:sign_type => valid_attributes}, valid_session
        }.to change(SignType, :count).by(1)
      end

      it "assigns a newly created sign_type as @sign_type" do
        post :create, {:sign_type => valid_attributes}, valid_session
        assigns(:sign_type).should be_a(SignType)
        assigns(:sign_type).should be_persisted
      end

      it "redirects to the created sign_type" do
        post :create, {:sign_type => valid_attributes}, valid_session
        response.should redirect_to(SignType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sign_type as @sign_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        SignType.any_instance.stub(:save).and_return(false)
        post :create, {:sign_type => {}}, valid_session
        assigns(:sign_type).should be_a_new(SignType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SignType.any_instance.stub(:save).and_return(false)
        post :create, {:sign_type => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sign_type" do
        sign_type = SignType.create! valid_attributes
        # Assuming there are no other sign_types in the database, this
        # specifies that the SignType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SignType.any_instance.should_receive(:update).with({'sign_value' => 'params'})
        put :update, {:id => sign_type.to_param, :sign_type => {'sign_value' => 'params'}}, valid_session
      end

      it "assigns the requested sign_type as @sign_type" do
        sign_type = SignType.create! valid_attributes
        put :update, {:id => sign_type.to_param, :sign_type => valid_attributes}, valid_session
        assigns(:sign_type).should eq(sign_type)
      end

      it "redirects to the sign_type" do
        sign_type = SignType.create! valid_attributes
        put :update, {:id => sign_type.to_param, :sign_type => valid_attributes}, valid_session
        response.should redirect_to(sign_type)
      end
    end

    describe "with invalid params" do
      it "assigns the sign_type as @sign_type" do
        sign_type = SignType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SignType.any_instance.stub(:save).and_return(false)
        put :update, {:id => sign_type.to_param, :sign_type => {}}, valid_session
        assigns(:sign_type).should eq(sign_type)
      end

      it "re-renders the 'edit' template" do
        sign_type = SignType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SignType.any_instance.stub(:save).and_return(false)
        put :update, {:id => sign_type.to_param, :sign_type => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sign_type" do
      sign_type = SignType.create! valid_attributes
      expect {
        delete :destroy, {:id => sign_type.to_param}, valid_session
      }.to change(SignType, :count).by(-1)
    end

    it "redirects to the sign_types list" do
      sign_type = SignType.create! valid_attributes
      delete :destroy, {:id => sign_type.to_param}, valid_session
      response.should redirect_to(sign_types_url)
    end
  end

end
